// wordCorrections.js

function applyWordCorrections(text) {
    return text
        .replace(/offer ings/g, 'offerings') // Corregir "offer ings" a "offerings"
        .replace(/well ness/g, 'wellness') // Corregir "well ness" a "wellness"
        .replace(/hes itate/g, 'hesitate') // Corregir "hes itate" a "hesitate"
        .replace(/ap ocal y ptic/g, 'apocalyptic')
        .replace(/Arm aged don/g, 'Armageddon')
        .replace(/myth ological/g, 'mythological')
        .replace(/Mount O th ros/g, 'Mount Othros')
        .replace(/bomb ings/g, 'bombings')
        .replace(/Hiro sh ima/g, 'Hiroshima')
        .replace(/Nag asaki/g, 'Nagasaki')
        .replace(/cat ac ly sm ic/g, 'cataclysmic')
        .replace(/devast ation/g, 'devastation')
        .replace(/pand em ics/g, 'pandemics')
        .replace(/catast rop hes/g, 'catastrophes')
        .replace(/It 's/g, "It's")
        .replace(/Ap ocal y pse/g, 'Apocalypse')
        .replace(/s too/g, "s too")
        .replace(/pat io/,"patio")
        .replace(/D reams/g, 'Dreams')
        .replace(/self - ref lection/g, 'self-reflection')
        .replace(/del ving/g, 'delving')
        .replace(/inner sel ves/g, 'inner selves')
        .replace(/well - being/g, 'well-being')
        .replace(/summar ization/g, 'summarization')
        .replace(/breat htaking/g, 'breathtaking')
        .replace(/ad orned/g, 'adorned')
        .replace(/casc ading/g, 'cascading')
        .replace(/silhou ette/g, 'silhouette')
        .replace(/cher ishing/g, 'cherishing')
        .replace(/cel estial/g, 'celestial')
        .replace(/un par alle led/g, 'unparalleled')
        .replace(/te em ing/g, 'teeming')
        .replace(/symbol ized/g, 'symbolized')
        .replace(/reb irth/g, 'rebirth')
        .replace(/hand -in -hand/g, 'hand-in-hand')
        .replace(/dazz ling/g, 'dazzling')
        .replace(/sw elled/g, 'swelled')
        .replace(/cher ishing/g, 'cherishing')
        .replace(/bea uty/g, 'beauty')
        .replace(/si lhou ette/g, 'silhouette')
        .replace(/cer tain ty/g, 'certainty')
        .replace(/te em ing/g, 'teeming')
        .replace(/par alle l/g, 'parallel')
        .replace(/al one/g, 'alone')
        .replace(/life 's/g, "life's")
        .replace(/capt iv ating/g, 'captivating')
        .replace(/sh immer ing/g, 'shimmering')
        .replace(/brilli antly/g, 'brilliantly')
        .replace(/gl ided/g, 'glided')
        .replace(/grace fully/g, 'gracefully')
        .replace(/enchant ing/g, 'enchanting')
        .replace(/hypnot ic/g, 'hypnotic')
        .replace(/mel odies/g, 'melodies')
        .replace(/entr anced/g, 'entranced')
        .replace(/sym phony/g, 'symphony')
        .replace(/couldn 't/g, 'couldn\'t')
        .replace(/harmonic ious/g, 'harmonious')
        .replace(/spl endor/g, 'splendor')
        .replace(/dream like/g, 'dreamlike')
        .replace(/const ell ations/g, 'constellations')
        .replace(/sh immer ing/g, 'shimmering')
        .replace(/et here al/g, 'ethereal')
        .replace(/ever - changing/g, 'ever-changing')
        .replace(/ench ant ing/g, 'enchanting')
        .replace(/rust ling/g, 'rustling')
        .replace(/not h ings/g, 'nothings')
        .replace(/orn ate/g, 'ornate')
        .replace(/intric ately/g, 'intricately')
        .replace(/un ach ie vable/g, 'unachievable')
        .replace(/sub conscious/g, 'subconscious')
        .replace(/kind led/g, 'kindled')
        .replace(/et here al/g, 'ethereal')
        .replace(/ind el ible/g, 'indelible')
        .replace(/can yon/g, 'canyon')
        .replace(/tow ering/g, 'towering')
        .replace(/perme ate/g, 'permeate')
        .replace(/nerv ously/g, 'nervously')
        .replace(/eve ning/g, 'evening')
        .replace(/tor ches/g, 'torches')
        .replace(/ha unting/g, 'haunting')
        .replace(/flick ering/g, 'flickering')
        .replace(/fl ute/g, 'flute')
        .replace(/ra zed/g, 'razed')
        .replace(/lab yrinth/g, 'labyrinth')
        .replace(/civil izations/g, 'civilizations')
        .replace(/it itude/g, 'fortitude')
        .replace(/un sh ak able/g, 'unshakeable')
        .replace(/un im agin able/g, 'unimaginable')
        .replace(/et ched/g, 'etched')
        .replace(/fate ful/g, 'fateful')
        .replace(/heart land/g, 'heartland')
        .replace(/conce aling/g, 'concealing')
        .replace(/late - night/g, 'late-night')
        .replace(/stealth ily/g, 'stealthily')
        .replace(/wasn ’ t/g, 'wasn\'t')
        .replace(/men acing ly/g, 'menacingly')
        .replace(/un controll ably/g, 'uncontrollably')
        .replace(/hor rifying/g, 'horrifying')
        .replace(/facult ies/g, 'faculties')
        .replace(/ne ared/g, 'neared')
        .replace(/un fore seen/g, 'unforeseen')
        .replace(/la ir/g, 'lair')
        .replace(/gl immer/g, 'glimmer')
        .replace(/fant ast ical/g, 'fantastical')
        .replace(/advent urous/g, 'adventurous')
        .replace(/imagin ative/g, 'imaginative')
        .replace(/escap ades/g, 'escapades')
        .replace(/morph ing/g, 'morphing')
        .replace(/wh ims y/g, 'whimsy')
        .replace(/palp able/g, 'palpable')
        .replace(/m uffled/g, 'muffled')
        .replace(/sn oring/g, 'snoring')
        .replace(/e erie/g, 'eerie')
        .replace(/ta unting ly/g, 'tauntingly')
        .replace(/Em ily/g, 'Emily')
        .replace(/lur king/g, 'lurking')
        .replace(/suff oc ating/g, 'suffocating')
        .replace(/Johns ons/g, 'Johnsons')
        .replace(/Smith s/g, 'Smiths')
        .replace(/villagers/g, 'villagers')
        .replace(/obs c uring/g, 'obscuring')
        .replace(/une ase/g, 'unease')
        .replace(/deaf ening/g, 'deafening')
        .replace(/terr ified/g, 'terrified')
        .replace(/en flames/g, 'in flames')
        .replace(/infer no/g, 'inferno')
        .replace(/scrambled/g, 'scrambled')
        .replace(/deaf ening/g, 'deafening')
        .replace(/grows/g, 'grows')
        .replace(/consp ired/g, 'conspired')
        .replace(/im agin able/g, 'imaginable')
        .replace(/apocalyptic/g, 'apocalyptic')
        .replace(/dec imated/g, 'decimated')
        .replace(/never - ending/g, 'never-ending')
        .replace(/ret ribution/g, 'retribution')
        .replace(/de arly/g, 'dearly')
        .replace(/dark est/g, 'darkest')
        .replace(/D reams/g, 'Dreams')
        .replace(/self - ref lection/g, 'self-reflection')
        .replace(/del ving/g, 'delving')
        .replace(/cre ak/g, 'creak')
        .replace(/flick ers/g, 'flickers')
        .replace(/paraly zed/g, 'paralyzed')
        .replace(/lur k/g, 'lurk')
        .replace(/dr ags/g, 'drags')
        .replace(/eman ating/g, 'emanating')
        .replace(/worst - case/g, 'worst-case')
        .replace(/conj uring/g, 'conjuring')
        .replace(/grow ling/g, 'growling')
        .replace(/stal ks/g, 'stalks')
        .replace(/gl int/g, 'glint')
        .replace(/b ares/g, 'bares')
        .replace(/f anged/g, 'fanged')
        .replace(/night mar/g, 'nightmare')
        .replace(/unf olds/g, 'unfolds')
        .replace(/labyrinth ine/g, 'labyrinthine')
        .replace(/gro tes que/g, 'grotesque')
        .replace(/will s/g, 'wills')
        .replace(/ins idious/g, 'insidious')
        .replace(/dis orientation/g, 'disorientation')
        .replace(/helpless ness/g, 'helplessness')
        .replace(/rh yme/g, 'rhyme')
        .replace(/dist orting/g, 'distorting')
        .replace(/deep ens/g, 'deepens')
        .replace(/labyrinth ine/g, 'labyrinthine')
        .replace(/alley way/g, 'alleyway')
        .replace(/shadow y/g, 'shadowy')
        .replace(/per v ades/g, 'pervades')
        .replace(/un rel enting/g, 'unrelenting')
        .replace(/sem blance/g, 'semblance')
        .replace(/ab yss/g, 'abyss')
        .replace(/nightmarees/g, 'nightmares')
        .replace(/black ened/g, 'blackened')
        .replace(/pur g atory/g, 'purgatory')
        .replace(/m ories/g, 'memories')
        .replace(/unb ear/g, 'unbear')
        .replace(/qu icks/g, 'quicks')
        .replace(/dizz ying/g, 'dizzying')
        .replace(/int rospective/g, 'introspective')
        .replace(/nightmare ish/g, 'nightmarish')
        .replace(/conf ines/g, 'confines')
        .replace(/intertw ined/g, 'intertwined')
        .replace(/unb ear able/g, 'unbearable')
        .replace(/suff ocated/g, 'suffocated')
        .replace(/sp arks/g, 'sparks')
        .replace(/pitch - black/g, 'pitch-black')
        .replace(/fle eting/g, 'fleeting')
        .replace(/gl imm ers/g, 'glimmers')
        .replace(/head - on/g, 'head-on')
        .replace(/Mor phe us/g, 'Morpheus')
        .replace(/sol ace/g, 'solace')
        .replace(/celest ial/g, 'celestial')
        .replace(/shroud ed/g, 'shrouded')
        .replace(/omin ous/g, 'ominous')
        .replace(/whisper ing/g, 'whispering')
        .replace(/think able/g, 'thinkable')
        .replace(/te eter ing/g, 'teetering')
        .replace(/danger ously/g, 'dangerously')
        .replace(/nothing ness/g, 'nothingness')
        .replace(/tum bling/g, 'tumbling')
        .replace(/end lessly/g, 'endlessly')
        .replace(/gn aw ing/g, 'gnawing')
        .replace(/void s/g, 'voids')
        .replace(/sle e pless/g, 'sleepless')
        .replace(/plag uing/g, 'plaguing')
        .replace(/dream ers/g, 'dreamers')
        .replace(/advers ity/g, 'adversity')
        .replace(/tra iled/g, 'trailed')
        .replace(/bum ps/g, 'bumps')
        .replace(/ex cit ement/g, 'excitement')
        .replace(/gra ffiti/g, 'graffiti')
        .replace(/re ds/g, 'reds')
        .replace(/yellow s/g, 'yellows')
        .replace(/som ber/g, 'somber')
        .replace(/un n erving/g, 'unnerving')
        .replace(/speak able/g, 'speakable')
        .replace(/char ismatic/g, 'charismatic')
        .replace(/Re aper/g, 'Reaper')
        .replace(/re aver/g, 'reaper')
        .replace(/recol lections/g, 'recollections')
        .replace(/fore b oding/g, 'foreboding')
        .replace(/echo ing/g, 'echoing')
        .replace(/foot fall/g, 'footfall')
        .replace(/eman ate/g, 'emanate')
        .replace(/his sed/g, 'hissed')
        .replace(/col der/g, 'colder')
        .replace(/t ailed/g, 'tailed')
        .replace(/relent lessly/g, 'relentlessly')
        .replace(/didn 't/g, 'didn\'t')
        .replace(/treacher ous/g, 'treacherous')
        .replace(/for ging/g, 'forging')
        .replace(/other world ly/g, 'otherworldly')
        .replace(/mon olith/g, 'monolith')
        .replace(/bl azing/g, 'blazing')
        .replace(/dev our/g, 'devour')
        .replace(/succ um bed/g, 'succumbed')
        .replace(/ch asm/g, 'chasm')
        .replace(/obliv ion/g, 'oblivion')
        .replace(/ent w ined/g, 'entwined')
        .replace(/ev itably/g, 'inevitably')
        .replace(/unfor giving/g, 'unforgiving')
        .replace(/v ines/g, 'vines')
        .replace(/h ues/g, 'hues')
        .replace(/tight - fitting/g, 'tight-fitting')
        .replace(/eleg antly/g, 'elegantly')
        .replace(/night mare/g, 'nightmare')
        .replace(/en chant ing/g, 'enchanting')
        .replace(/Dream real m/g, 'Dreamrealm')
        .replace(/Night mare/g, 'Nightmare')
        .replace(/ens n are/g, 'ensnare')
        .replace(/uns us pect ing/g, 'unsuspecting')
        .replace(/clut ches/g, 'clutches')
        .replace(/succ umbing/g, 'succumbing')
        .replace(/oblivion ,/g, 'oblivion,')
        .replace(/Dream real m 's/g, 'Dreamrealm\'s')
        .replace(/fear ing/g, 'fearing')
        .replace(/newcom er/g, 'newcomer')
        .replace(/watch ful/g, 'watchful')
        .replace(/nav igated/g, 'navigated')
        .replace(/fear some/g, 'fearsome')
        .replace(/del ved/g, 'delved')
        .replace(/Night mare/g, 'Nightmare')
        .replace(/crypt ic/g, 'cryptic')
        .replace(/In trig ued/g, 'Intrigued')
        .replace(/en igm atic/g, 'enigmatic')
        .replace(/trig ued/g, 'triggered')
        .replace(/peril ous/g, 'perilous')
        .replace(/Ult imately/g, 'Ultimately')
        .replace(/met tle/g, 'mettle')
        .replace(/stead fast/g, 'steadfast')
        .replace(/m az es/g, 'mazes')
        .replace(/ens n aring/g, 'ensnaring')
        .replace(/unw ary/g, 'unwary')
        .replace(/travel er/g, 'traveler')
        .replace(/hor de/g, 'horde')
        .replace(/vict orious/g, 'victorious')
        .replace(/reve red/g, 'revered')
        .replace(/long - form/g, 'long-form')
        .replace(/ins ur mount able/g, 'insurmountable')
        .replace(/real ms/g, 'realms')
        .replace(/illum inate/g, 'illuminate')
        .replace(/men acing/g, 'menacing')
        .replace(/rot ting/g, 'rotting')
        .replace(/o oz ing/g, 'oozing')
        .replace(/shri eks/g, 'shrieks')
        .replace(/agon ized/g, 'agonized')
        .replace(/tor mented/g, 'tormented')
        .replace(/del usion/g, 'delusion')
        .replace(/Des per ately/g, 'Desperately')
        .replace(/nest led/g, 'nestled')
        .replace(/superhero es/g, 'superheroes')
        .replace(/LE GO/g, 'LEGO')
        .replace(/cast les/g, 'castles')
        .replace(/bas kets/g, 'baskets')
        .replace(/l oll ip ops/g, 'lollipops')
        .replace(/rad iated/g, 'radiated')
        .replace(/sug ary/g, 'sugary')
        .replace(/agon izing/g, 'agonizing')
        .replace(/ghost ly/g, 'ghostly')
        .replace(/appar itions/g, 'apparitions')
        .replace(/res orted/g, 'resorted')
        .replace(/dist ra ught/g, 'distraught')
        .replace(/children 's/g, "children's")
        .replace(/quest s/g, 'quests')
        .replace(/folk lore/g, 'folklore')
        .replace(/m az es/g, 'mazes')
        .replace(/clutches and/g, 'clutches and')
        .replace(/Sweet Dreams/g, 'Sweet Dreams')
        .replace(/swe ets/g, 'sweets')
        .replace(/ghost ly/g, 'ghostly')
        .replace(/appar itions/g, 'apparitions')
        .replace(/fear less/g, 'fearless')
        .replace(/self - discovery/g, 'self-discovery')
        .replace(/m az es/g, 'mazes')
        .replace(/turned . /g, 'turned.')
        .replace(/ Sweet Dreams /g, ' Sweet Dreams ')
        .replace(/child ren /g, 'children ')
        .replace(/fear less /g, 'fearless ')
        .replace(/head - on /g, 'head-on ')
        .replace(/self - discovery /g, 'self-discovery ')
        .replace(/Tim my/g, 'Timmy')
        .replace(/bed time/g, 'bedtime')
        .replace(/grow l/g, 'growl')
        .replace(/cur dling/g, 'curdling')
        .replace(/p iqu ed/g, 'piqued')
        .replace(/eer ily/g, 'eerily')
        .replace(/encounter ing/g, 'encountering')
        .replace(/th inking/g, 'thinking')
        .replace(/clut ched/g, 'clutched')
        .replace(/des ks/g, 'desks')
        .replace(/grandmother 's/g, "grandmother's")
        .replace(/night marish/g, 'nightmarish')
        .replace(/else ’ s/g, "else's")
        .replace(/un f azed/g, 'unfazed')
        .replace(/bark ing/g, 'barking')
        .replace(/scree ching/g, 'screeching')
        .replace(/pier ced/g, 'pierced')
        .replace(/slic ing/g, 'slicing')
        .replace(/T err ified/g, 'Terrified')
        .replace(/st ren uous/g, 'strenuous')
        .replace(/lib ido/g, 'libido')
        .replace(/rest ful/g, 'restful')
        .replace(/nights ' s/g, "nights's")
        .replace(/l umber/g, 'lumber')
        .replace(/she pherd/g, 'shepherd')
        .replace(/ab ode/g, 'abode')
        .replace(/flow ers/g, 'flowers')
        .replace(/sway ing/g, 'swaying')
        .replace(/se rene/g, 'serene')
        .replace(/bab bling/g, 'babbling')
        .replace(/bro ok/g, 'brook')
        .replace(/shack les/g, 'shackles')
        .replace(/sh aky/g, 'shaky')
        .replace(/un ty ing/g, 'untying')
        .replace(/be aded/g, 'beaded')
        .replace(/expl oration/g, 'exploration')
        .replace(/overt aken/g, 'overtaken')
        .replace(/envelop ed/g, 'enveloped')
        .replace(/bur d ened/g, 'burdened')
        .replace(/trib ulations/g, 'tribulations')
        .replace(/ev olving/g, 'evolving')
        .replace(/un wa vering/g, 'unwavering')
        .replace(/bound less/g, 'boundless')
        .replace(/priorit ize/g, 'prioritize')
        .replace(/dem ean ing/g, 'demeaning')
        .replace(/implant ing/g, 'implanting')
        .replace(/bou levard/g, 'boulevard')
        .replace(/B reat he/g, 'Breathe')
        .replace(/F arm/g, 'Farm')
        .replace(/bout ique /g, 'boutique ')
        .replace(/Art isan 's/g, "Artisan's")
        .replace(/Art isan/g, 'Artisan')
        .replace(/st ric ken/g, 'stricken')
        .replace(/topp ling/g, 'toppling')
        .replace(/har med/g, 'harmed')
        .replace(/mirac ulous/g, 'miraculous')
        .replace(/met ropolis/g, 'metropolis')
        .replace(/bust ling/g, 'bustling')
        .replace(/Among st/g, 'Amongst')
        .replace(/Work er/g, 'Worker')
        .replace(/grapp ling/g, 'grappling')
        .replace(/2 4 \/ 7/g, '24/7')
        .replace(/c ig arette/g, 'cigarette')
        .replace(/reserv ation/g, 'reservation')
        .replace(/Instruction\s*:\s.*$|Response\s*:/gm, '')
        .replace(/ thr illed/g, ' thrilled') // Corregir "thr illed" a "thrilled"
        .replace(/offer ings/g, 'offerings') // Corregir "offer ings" a "offerings"
        .replace(/well ness/g, 'wellness') // Corregir "well ness" a "wellness"
        .replace(/hes itate/g, 'hesitate') // Corregir "hes itate" a "hesitate"
        .replace(/connect s/g, 'connects') // Corregir "connect s" a "connects"
        .replace(/simpl ifies/g, 'simplifies') // Corregir "simpl ifies" a "simplifies"
        .replace(/trans parency/g, 'transparency') // Corregir "trans parency" a "transparency"
        .replace(/simpl ifying/g, 'simplifying') // Corregir "simpl ifying" a "simplifying"
        .replace(/trust worth iness/g, 'trustworthiness') // Corregir "trust worth iness" a "trustworthiness"
        .replace(/pam per/g, 'pamper') // Corregir "pam per" a "pamper"
        .replace(/brow se/g, 'browse') // Corregir "brow se" a "browse"
        .replace(/fing ert ips/g, 'fingertips') // Corregir "fing ert ips" a "fingertips"
        .replace(/mass ages/g, 'massages') // Corregir "mass ages" a "massages"
        .replace(/fac ials/g, 'facials') // Corregir "fac ials" a "facials"
        .replace(/car p entry/g, 'carpentry') // Corregir "car p entry" a "carpentry"
        .replace(/groom ing/g, 'grooming') // Corregir "groom ing" a "grooming"
        .replace(/sh aring/g, 'sharing') // Corregir "sh aring" a "sharing"
        .replace(/We'\sd/g, "We'd") // Corregir "We' d" a "We'd"
        .replace(/it'\ss/g, "it's") // Corregir "it' s" a "it's"
        .replace(/C\sertain\ssly/g, 'Certainly') // Corregir "C ertain ly" a "Certainly"
        .replace(/we'\s?re/g, "we're") // Corregir "we' re" a "we're"
        .replace(/convenient\ssly/g, 'conveniently') // Corregir "convenient ly" a "conveniently"
        .replace(/register ing/g, 'registering') // Corregir "register ing" a "registering"
        .replace(/promot ions/g, 'promotions') // Corregir "promot ions" a "promotions"
        .replace(/discount s/g, 'discounts') // Corregir "discount s" a "discounts"
        .replace(/hass le/g, 'hassle') // Corregir "hass le" a "hassle"
        .replace(/\bsimpl\sify\b/g, 'simplify')
        .replace(/\bReg\sistration\b/g, 'Registration')
        .replace(/\bseam\sless\b/g, 'seamless')
        .replace(/\bdiscover\sing\b/g, 'discovering')
        .replace(/\btail\lored\b/g, 'tailored')
        .replace(/Instruction:.*$/gm, '')
        .replace(/###/g, '') // Eliminar patrón "###"
        .replace(/cl icks/g, 'clicks') // Corregir "cl icks" a "clicks"
        .replace(/\n+/g, ' ') // Eliminar saltos de línea
        .replace(/\s+/g, ' ') // Reemplazar múltiples espacios con uno solo
        .replace(/D ear/g, "Dear") // Corregir "D ear" a "Dear"
        .replace(/Register ing/g, "Registering") // Corregir "Register ing" a "Registering"
        .replace(/prom pts/g, "prompts") // Corregir "prom pts" a "prompts"
        .replace(/tail ored/g, "tailored") // Corregir "tail ored" a "tailored"
        .replace(/misunder standing/g, "misunderstanding") // Corregir "misunder standing" a "misunderstanding"
        .replace(/I' m/g, "I'm") // Corregir "I' m" a "I'm"
        .replace(/clar ify/g, "clarify") // Corregir "clar ify" a "clarify"
        .replace(/Reg ardless/g, "Regardless") // Corregir "Reg ardless" a "Regardless"
        .replace(/there' s/g, "there's") // Corregir "there' s" a "there's")
        .replace(/chat bot/g, 'chatbot')
        .replace(/sex ually/g, 'sexually')
        .replace(/clar ification/g, 'clarification')
        .replace(/don' t/g, "don't")
        .replace(/d ild os/g, 'dildos')
        .replace(/retail ers/g, 'retailers')
        .replace(/special izing/g, 'specializing')
        .replace(/incon ven ience/g, 'inconvenience')
        .replace(/Ide ao a/g, 'Ideoa') // Corregir "Ide ao a" a "Ideoa"
        .replace(/special ize/g, 'specialize')
        .replace(/Mad am/g, 'Madam')
        .replace(/match making/g, 'matchmaking')
        .replace(/regret fully/g, 'regretfully')
        .replace(/ill icit/g, 'illicit')
        .replace(/cig arettes/g, 'cigarettes')
        .replace(/intim acy/g, 'intimacy')
        .replace(/enc ounters/g, 'encounters')
        .replace(/cater ing/g, 'catering')
        .replace(/detail ing/g, 'detailing')
        .replace(/rent als/g, 'rentals')
        .replace(/C ertain ly/g, 'Certainly')
        .replace(/tax is/g, 'taxis')
        .replace(/Tax i/g, 'Taxi')
        .replace(/T ap/g, 'Tap')
        .replace(/Transport ation/g, 'Transportation')
        .replace(/prohib ited/g, 'prohibited')
        .replace(/refr ain/g, 'refrain')
        .replace(/stri ve/g, 'strive')
        .replace(/sinc ere/g, 'sincere')
        .replace(/ap ologies/g, 'apologies')
        .replace(/ar isen/g, 'arisen')
        .replace(/toler ate/g, 'tolerate')
        .replace(/ab usive/g, 'abusive')
        .replace(/der og atory/g, 'derogatory')
        .replace(/C\sertain\ssly/g, 'Certainly')
        .replace(/tut oring/g, 'tutoring')
        .replace(/sty list/g, 'stylist')
        .replace(/hand yman/g, 'handyman')
        .replace(/le aky/g, 'leaky')
        .replace(/f auc et/g, 'faucet')
        .replace(/un reg ulated/g, 'unregulated')
        .replace(/av en ues/g, 'avenues')
        .replace(/fulfill ing/g, 'fulfilling')
        .replace(/reput able/g, 'reputable')
        .replace(/cons ens ual/g, 'consensual')
        .replace(/creat ors/g, 'creators')
        .replace(/imp erson al/g, 'impersonal')
        .replace(/tim ely/g, 'timely')
        .replace(/G room ing/g, 'Grooming')
        .replace(/S itting/g, 'Sitting')
        .replace(/Brow se/g, 'Browse')
        .replace(/re habil itation/g, 'rehabilitation')
        .replace(/squ ir rel s/g, 'squirrels')
        .replace(/In clude/g, 'Include')
        .replace(/out lin ing/g, 'outlining')
        .replace(/Inst ruction\s*:\s.*$/gm, '')
        .replace(/gu est/g, 'guest')
        .replace(/transparent ly/g, 'transparently')
        .replace(/alcohol ic/g, 'alcoholic')
        .replace(/brows ing/g, 'browsing')
        .replace(/fraud ulent/g, 'fraudulent')
        .replace(/sc ams/g, 'scams')
        .replace(/ad her ing/g, 'adhering')
        .replace(/market pl aces/g, 'marketplaces')
        .replace(/unple asant/g, 'unpleasant')
        .replace(/res olving/g, 'resolving')
        .replace(/G reet ings/g, 'Greetings')
        .replace(/Inter pre ting/g, 'Interpreting')
        .replace(/sim ulating/g, 'simulating')
        .replace(/symbol ism/g, 'symbolism')
        .replace(/D ream/g, 'Dream')
        .replace(/cl aps/g, 'claps')
        .replace(/zomb ies/g, 'zombies')
        .replace(/symbol ize/g, 'symbolize')
        .replace(/Th r iller/g, 'Thriller')
        .replace(/ev oke/g, 'evoke')
        .replace(/symbol izes/g, 'symbolizes')
        .replace(/ light ness/g, 'lightness')
        .replace(/e up hor ia/g, 'euphoria')
        .replace(/dep ression/g, 'depression')
        .replace(/pr imal/g, 'primal')
        .replace(/were w olves/g, 'werewolves')
        .replace(/rew olves/g, 'rewolves')
        .replace(/metam orph osis/g, 'metamorphosis')
        .replace(/al beit/g, 'albeit')
        .replace(/contempl ation/g, 'contemplation')
        .replace(/Z omb ies/g, 'Zombies')
        .replace(/th r iller/g, 'thriller')
        .replace(/sol itude/g, 'solitude')
        .replace(/surreal ism/g, 'surrealism')
        .replace(/Thr iller/g, 'Thriller')
        .replace(/thr ills/g, 'thrills')
        .replace(/Thr iller/g, 'Thriller')
        .replace(/anx ieties/g, 'anxieties')
        .replace(/anthrop omorphic/g, 'anthropomorphic')
        .replace(/r idd led/g, 'riddled')
        .replace(/an o de/g, 'anode')
        .replace(/tim eless/g, 'timeless')
        .replace(/fores h adow ing/g, 'foreshadowing')
        .replace(/Em otion ally/g, 'Emotionally')
        .replace(/tra umas/g, 'traumas')
        .replace(/cath ars is/g, 'catharsis')
        .replace(/Se eking/g, 'Seeking')
        .replace(/journal ing/g, 'journaling')
        .replace(/distress ful/g, 'distressful')
        .replace(/Res olution/g, 'Resolution');

}
